USE ArticleSchema
INSERT INTO Keywords (KeywordsID, KeywordsName) VALUES
('Kw001', 'Evolutionary Forest'),
('Kw002', 'Regression'),
('Kw003', 'Forest'),
('Kw004', 'Benchmark Problems'),
('Kw005', 'Genetic Programming'),
('Kw006', 'Decision Tree'),
('Kw007', 'Regression Benchmark'),
('Kw008', 'Evolutionary Algorithms'),
('Kw009', 'Ensemble Learning'),
('Kw010', 'Information Fusion'),
('Kw011', 'Feature Construction'),
('Kw012', 'Multiobjective Optimization'),
('Kw013', 'Swarm Optimization'),
('Kw014', 'Transfer Learning'),
('Kw015', 'Reinforcement Learning'),
('Kw016', 'Convolutional Neural Networks'),
('Kw017', 'Symbolic Regression'),
('Kw018', 'Deep Learning'),
('Kw019', 'Image Classification'),
('Kw020', 'Document Classification'),
('Kw021', 'Sequence-to-Sequence'),
('Kw022', 'Performance Prediction'),
('Kw023', 'Neural Networks');
